version: '3'

services:
  node-app:
    depends_on:
      - mongo
  
  mongo: 
    image: mongo
    volumes:
      - mongo:/data/db

  nginx: 
    image: nginx:stable-alpine
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

volumes:
  mongo: