version: '3'

services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: ${NODE_ENV}
    environment:
        - NODE_ENV=${NODE_ENV}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: npm run start

  mongo: 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}