version: '3'

services:
  node-app:
    image: imokhonko/node-app:dev
    build: 
      context: .
      args: 
        NODE_ENV: development
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
    volumes:
      - ./:/application
    command: npm run start

  mongo: 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin