version: '3'

services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/application
    command: npm run dev