name: Docker Image CI on DEVELOPMENT

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: imokhonko/node-app
        tags: dev
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    # - name: Deploy
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.DEV_INSTANCE_IP_ADDRESS }}
    #     username: root
    #     password: ${{ secrets.INSTANCE_ROOT_PASSWORD }}
    #     script: |
    #       cd application
    #       git pull origin dev
    #       npm run docker:prod


