name: Docker Image CI on QA

on:
  push:
    branches: [ qa ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: imokhonko/node-app
        tags: qa
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.QA_INSTANCE_IP_ADDRESS }}
        username: root
        password: ${{ secrets.INSTANCE_ROOT_PASSWORD }}
        script: |
          cd application
          git checkout qa
          git pull origin qa
          docker stack deploy -c docker-compose.yml -c docker-compose.qa.yml application


